#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WRITERS_NUM 3
#define READERS_NUM 5

#define READER_SLEEP_TIME 2
#define WRITER_SLEEP_TIME 2

#define ACTIVE_WRITERS 0
#define WAITING_WRITERS 1
#define ACTIVE_READERS 2
#define ACCESS 3

#define ITERS_NUM 7

#endif
